<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SwiftDrop.Desktop</RootNamespace>
    <AssemblyName>SwiftDrop.Desktop</AssemblyName>
    <ApplicationTitle>SwiftDrop</ApplicationTitle>
    <ApplicationId>in.sanskar.swiftdrop.desktop</ApplicationId>
    <Version>1.0.0</Version>
    <RuntimeIdentifiers>linux-x64;linux-arm64;win-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SwiftDrop.Core/SwiftDrop.Core.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
  </ItemGroup>
</Project>
