<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>SwiftDrop.ShareExtension</RootNamespace>
    <AssemblyName>SwiftDrop.ShareExtension</AssemblyName>
    <IsAppExtension>true</IsAppExtension>
    <InfoPlist>Info.plist</InfoPlist>
    <ApplicationTitle>SwiftDrop Share</ApplicationTitle>
    <ApplicationId>in.sanskar.swiftdrop.share</ApplicationId>
    <ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    <CodesignEntitlements>Platforms/iOS/Entitlements.plist</CodesignEntitlements>
    <CodesignConfigureDependsOn>$(CodesignConfigureDependsOn);DisableCodesignInSimulator</CodesignConfigureDependsOn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SwiftDrop.Core/SwiftDrop.Core.csproj" />
  </ItemGroup>
  <Target Name="DisableCodesignInSimulator" Condition="'$(SdkIsSimulator)' == 'true'">
    <PropertyGroup>
      <EnableCodeSigning>false</EnableCodeSigning>
    </PropertyGroup>
  </Target>
</Project>
